### ISSUE TITLE
This package is linux only ModuleNotFoundError: No module named 'fcntl'

### ISSUE THREAD

**Issue by FurkanGozukara** [NVlabs/Sana#19]
Why you are using something unix only for serious?

Are you selling GPUs to only linux users? 

```
G:\Sana_v1>cd Sana

G:\Sana_v1\Sana>call venv\Scripts\activate.bat
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "G:\Sana_v1\Sana\app\app_sana.py", line 35, in <module>
    from app.sana_pipeline import SanaPipeline
  File "G:\Sana_v1\Sana\app\sana_pipeline.py", line 29, in <module>
    from diffusion.data.datasets.utils import *
  File "G:\Sana_v1\Sana\diffusion\data\__init__.py", line 1, in <module>
    from .datasets import *
  File "G:\Sana_v1\Sana\diffusion\data\datasets\__init__.py", line 1, in <module>
    from .sana_data import SanaImgDataset, SanaWebDataset
  File "G:\Sana_v1\Sana\diffusion\data\datasets\sana_data.py", line 32, in <module>
    from diffusion.data.wids import ShardListDataset, ShardListDatasetMulti, lru_json_load
  File "G:\Sana_v1\Sana\diffusion\data\wids\__init__.py", line 7, in <module>
    from .wids import (
  File "G:\Sana_v1\Sana\diffusion\data\wids\wids.py", line 42, in <module>
    from .wids_dl import download_and_open
  File "G:\Sana_v1\Sana\diffusion\data\wids\wids_dl.py", line 18, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'
Press any key to continue . . .

```

**Comment by lawrence-cj** [comment]
refer to: https://github.com/NVlabs/Sana/commit/d1efac58766631c0417c38b1416cc552345ffc40
Besides, please treat open source projects with courtesy and polite.

**Comment by FurkanGozukara** [comment]
@lawrence-cj i am so sorry for sounding like rude

i had to spent exactly more than 5 hours to fix all errors to make it run so i was really tired yesterday night at 4 am

finally made it work on windows

![image](https://github.com/user-attachments/assets/ddb9c5b1-d2b8-4afa-ba18-6a0b34d78ae2)

**Comment by lawrence-cj** [comment]
thanks for your hard work.
