### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for SanaMS:

### ISSUE THREAD

**Issue by win10ogod** [NVlabs/Sana#20]
PS E:\Sana-main> python app/app_sana.py --config=configs/sana_config/1024ms/Sana_1600M_img1024.yaml --model_path=E:\ComfyUI-aki-v1.3\models\checkpoints\Sana_1600M_1024px.pth
2024-11-22 09:11:06 - [Sana] - INFO - Sampler flow_dpm-solver, flow_shift: 3.0
2024-11-22 09:11:06 - [Sana] - INFO - Inference with torch.bfloat16, PAG guidance layer: [8]
[DC-AE] Loading model from mit-han-lab/dc-ae-f32c32-sana-1.0
2024-11-22 09:11:23 - [Sana] - WARNING - use pe: False, position embed interpolation: 1.0, base size: 32
2024-11-22 09:11:23 - [Sana] - WARNING - attention type: linear; ffn type: glumbconv; autocast linear attn: False
2024-11-22 09:11:37 - [Sana] - INFO - use_fp32_attention: False
2024-11-22 09:11:37 - [Sana] - INFO - SanaMS:SanaMS_1600M_P1_D20,Model Parameters: 1,602,742,432
[Sana] Loading model from E:\ComfyUI-aki-v1.3\models\checkpoints\Sana_1600M_1024px.pth
Traceback (most recent call last):
  File "E:\Sana-main\app\app_sana.py", line 194, in <module>
    pipe.from_pretrained(model_path)
  File "E:\Sana-main\app\app\sana_pipeline.py", line 170, in from_pretrained
    missing, unexpected = self.model.load_state_dict(state_dict, strict=False)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jmes1\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 2215, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SanaMS:
        size mismatch for y_embedder.y_embedding: copying a param with shape torch.Size([300, 2304]) from checkpoint, the shape in current model is torch.Size([2240, 1536]).
        size mismatch for y_embedder.y_proj.fc1.weight: copying a param with shape torch.Size([2240, 2304]) from checkpoint, the shape in current model is torch.Size([2240, 1536]).

**Comment by lawrence-cj** [comment]
Any changes of the code? I don't understand why the `1536` channel is shown in your logs.

**Comment by win10ogod** [comment]
> Any changes of the code? I don't understand why the `1536` channel is shown in your logs.

Maybe the inference code isn't complete yet?
This paragraph explains that llm should be replaced (I used qwen2.5 1.5b for testing)
https://github.com/NVlabs/Sana/blob/d1efac58766631c0417c38b1416cc552345ffc40/diffusion/model/builder.py#L44

**Comment by lawrence-cj** [comment]
The released model only support gemma-2-2b-it FYI
