### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by endman100** [NVlabs/Sana#27]
This is a very good project. Thank you for the team's contribution.
I would like to know if there will be Windows support without Triton? 

Thanks!

**Comment by brayevalerien** [comment]
There are some precompiled Triton wheels for [here](https://github.com/woct0rdho/triton-windows/releases). I got Sana working on Windows when it came out, it should still be possible now.

**Comment by lawrence-cj** [comment]
The current inference and training code is not using Triton. You should run on your windows smoothly.

**Comment by Lyken17** [comment]
@lawrence-cj if not using, let's disable it first?

**Comment by lawrence-cj** [comment]
It would be better to check if the triton is available to import rather than disable it directly. @Lyken17

**Comment by nitinmukesh** [comment]
@CRCODE22 

What is not working. Post the error log from command prompt.

**Comment by endman100** [comment]
Thanks to all comment, I pulled the latest commits, but I still couldn't execute them. So, I made some tweaks to the program myself, which might not have been the correct way to modify it, but I was able to successfully open app_sana and run the example program in Windows11.
1. Modified Sana/diffusion/model/dc_ae/efficientvit/models/nn/triton_rms_norm.py:
Commented out the lines "import triton" and "import triton.language as tl"
Removed all instances of : "tl.constexpr" and "@triton.jit".
![image](https://github.com/user-attachments/assets/6e9a87bb-41fc-4445-8b6a-cb22879c1441)


2. Created a fcntl.py file.
Created a fcntl.py file to prevent errors caused by the absence of the fcntl module on Windows. The code is as follows:
``` python
def fcntl(fd, op, arg=0):
    return 0

def ioctl(fd, op, arg=0, mutable_flag=True):
    if mutable_flag:
        return 0
    else:
        return ""

def flock(fd, op):
    return

def lockf(fd, operation, length=0, start=0, whence=0):
    return
```

![image](https://github.com/user-attachments/assets/7d1923ec-c5eb-48e4-a81d-95af9f9a9886)

**Comment by endman100** [comment]
> where will the `fcntl ` module be used?

In ./diffusion/data/wids/wids_dl.py file line 18
Windows does not come with the fcntl module by default.

**Comment by CRCODE22** [comment]
So far any attempts of using Sana under Windows 11 with a Nvidia Geforce RTX 4060 TI 16GB VRAM and 128GB System Ram have failed because of installation problems not even the so called claimed made for Windows versions of this work and I followed every installation instructions to the letter (some of them are even incomplete). It is in a way funny that Nvidia used to be very focused on Windows and not even their latest visual model is officially supported on it now.

**Comment by Lyken17** [comment]
Seems to disable wids related module during the inference should work. 

Hi @endman100 @nitinmukesh , in which step you are blocked? Installation or inferecne, if the later, can you share the inference scripts?

**Comment by FurkanGozukara** [comment]
i had to make a lot of pipeline fixes for to make it work  on windows - so many only linux available libraries used

**Comment by Lyken17** [comment]
@FurkanGozukara can you share your solution and (if possible) draft PR? I agree that we may put too many linux pkgs during development and hence want to trim the dependency

**Comment by nitinmukesh** [comment]
@Lyken17 

I'm not blocked, I made it work within 1 hour on Windows and using it.

To fix the Linux specific issues

1. Replace all instances of
fcntl
with
portalocker

In
Sana\diffusion\data\wids\wids_dl.py
Sana\diffusion\data\wids\wids_mmtar.py

and 
pip install portalocker

**Comment by CRCODE22** [comment]
> @FurkanGozukara can you share your solution and (if possible) draft PR? I agree that we may put too many linux pkgs during development and hence want to trim the dependency

He will not share or contribute for free he paywalls most of his stuff money is what drives him even tough he uses so much from the open source community who do things for free he needs to make a profit out of it.

**Comment by brayevalerien** [comment]
> > @FurkanGozukara can you share your solution and (if possible) draft PR? I agree that we may put too many linux pkgs during development and hence want to trim the dependency
> 
> He will not share or contribute for free he paywalls most of his stuff money is what drives him even tough he uses so much from the open source community who do things for free he needs to make a profit out of it.

Seriously though. I don't even get how he isn't banned from Github and why I'm seing him even though I blocked him. He's so disrespectfull it's even more irritating that he is promoting his scamy content on Github in addition to HuggingFace and Reddit.

**Comment by nitinmukesh** [comment]
@CRCODE22 

Are you still struggling to make it work on Windows?

**Comment by CRCODE22** [comment]
> @CRCODE22
> 
> Are you still struggling to make it work on Windows? I will look at it again.

Yes I still have not managed to make it work and I follow the instructions exactly.

(sana) K:\Sana_win>python app\app_sana.py --config configs\sana_config\1024ms\Sana_1600M_img1024.yaml --model_path Efficient-Large-Model\Sana_1600M_1024px\checkpoints\Sana_1600M_1024px.pth
A matching Triton is not available, some optimizations will not be enabled
Traceback (most recent call last):
  File "e:\anaconda3\envs\sana\lib\site-packages\xformers\__init__.py", line 57, in _is_triton_available
    import triton  # noqa
  File "e:\anaconda3\envs\sana\lib\site-packages\triton\__init__.py", line 20, in <module>
    from .runtime import (
  File "e:\anaconda3\envs\sana\lib\site-packages\triton\runtime\__init__.py", line 1, in <module>
    from .autotuner import (Autotuner, Config, Heuristics, autotune, heuristics)
  File "e:\anaconda3\envs\sana\lib\site-packages\triton\runtime\autotuner.py", line 9, in <module>
    from ..testing import do_bench, do_bench_cudagraph
  File "e:\anaconda3\envs\sana\lib\site-packages\triton\testing.py", line 7, in <module>
    from . import language as tl
  File "e:\anaconda3\envs\sana\lib\site-packages\triton\language\__init__.py", line 4, in <module>
    from . import math
  File "e:\anaconda3\envs\sana\lib\site-packages\triton\language\math.py", line 1, in <module>
    from . import core
  File "e:\anaconda3\envs\sana\lib\site-packages\triton\language\core.py", line 10, in <module>
    from ..runtime.jit import jit
  File "e:\anaconda3\envs\sana\lib\site-packages\triton\runtime\jit.py", line 12, in <module>
    from ..runtime.driver import driver
  File "e:\anaconda3\envs\sana\lib\site-packages\triton\runtime\driver.py", line 1, in <module>
    from ..backends import backends
  File "e:\anaconda3\envs\sana\lib\site-packages\triton\backends\__init__.py", line 50, in <module>
    backends = _discover_backends()
  File "e:\anaconda3\envs\sana\lib\site-packages\triton\backends\__init__.py", line 43, in _discover_backends
    compiler = _load_module(name, os.path.join(root, name, 'compiler.py'))
  File "e:\anaconda3\envs\sana\lib\site-packages\triton\backends\__init__.py", line 12, in _load_module
    spec.loader.exec_module(module)
  File "e:\anaconda3\envs\sana\lib\site-packages\triton\backends\amd\compiler.py", line 2, in <module>
    from triton._C.libtriton import ir, passes, llvm, amd
ImportError: DLL load failed while importing libtriton: A dynamic link library (DLL) initialization routine failed.
Traceback (most recent call last):
  File "K:\Sana_win\app\app_sana.py", line 34, in <module>
    from app.sana_pipeline import SanaPipeline
  File "e:\anaconda3\envs\sana\lib\site-packages\app\sana_pipeline.py", line 28, in <module>
    from diffusion import DPMS, FlowEuler
  File "e:\anaconda3\envs\sana\lib\site-packages\diffusion\__init__.py", line 6, in <module>
    from .dpm_solver import DPMS
  File "e:\anaconda3\envs\sana\lib\site-packages\diffusion\dpm_solver.py", line 19, in <module>
    from .model import gaussian_diffusion as gd
  File "e:\anaconda3\envs\sana\lib\site-packages\diffusion\model\__init__.py", line 1, in <module>
    from .nets import *
  File "e:\anaconda3\envs\sana\lib\site-packages\diffusion\model\nets\__init__.py", line 1, in <module>
    from .sana import *
  File "e:\anaconda3\envs\sana\lib\site-packages\diffusion\model\nets\sana.py", line 25, in <module>
    from diffusion.model.builder import MODELS
  File "e:\anaconda3\envs\sana\lib\site-packages\diffusion\model\builder.py", line 24, in <module>
    from diffusion.model.dc_ae.efficientvit.ae_model_zoo import DCAE_HF
  File "e:\anaconda3\envs\sana\lib\site-packages\diffusion\model\dc_ae\efficientvit\ae_model_zoo.py", line 24, in <module>
    from ..efficientvit.models.efficientvit.dc_ae import DCAE, DCAEConfig, dc_ae_f32c32, dc_ae_f64c128, dc_ae_f128c512
  File "e:\anaconda3\envs\sana\lib\site-packages\diffusion\model\dc_ae\efficientvit\models\efficientvit\__init__.py", line 1, in <module>
    from .dc_ae import *
  File "e:\anaconda3\envs\sana\lib\site-packages\diffusion\model\dc_ae\efficientvit\models\efficientvit\dc_ae.py", line 25, in <module>
    from ...models.nn.act import build_act
  File "e:\anaconda3\envs\sana\lib\site-packages\diffusion\model\dc_ae\efficientvit\models\nn\__init__.py", line 2, in <module>
    from .drop import *
  File "e:\anaconda3\envs\sana\lib\site-packages\diffusion\model\dc_ae\efficientvit\models\nn\drop.py", line 24, in <module>
    from ...models.nn.ops import IdentityLayer, ResidualBlock
  File "e:\anaconda3\envs\sana\lib\site-packages\diffusion\model\dc_ae\efficientvit\models\nn\ops.py", line 24, in <module>
    from ...models.nn.norm import build_norm
  File "e:\anaconda3\envs\sana\lib\site-packages\diffusion\model\dc_ae\efficientvit\models\nn\norm.py", line 23, in <module>
    from ...models.nn.triton_rms_norm import TritonRMSNorm2dFunc
  File "e:\anaconda3\envs\sana\lib\site-packages\diffusion\model\dc_ae\efficientvit\models\nn\triton_rms_norm.py", line 18, in <module>
    import triton
  File "e:\anaconda3\envs\sana\lib\site-packages\triton\__init__.py", line 20, in <module>
    from .runtime import (
  File "e:\anaconda3\envs\sana\lib\site-packages\triton\runtime\__init__.py", line 1, in <module>
    from .autotuner import (Autotuner, Config, Heuristics, autotune, heuristics)
  File "e:\anaconda3\envs\sana\lib\site-packages\triton\runtime\autotuner.py", line 9, in <module>
    from ..testing import do_bench, do_bench_cudagraph
  File "e:\anaconda3\envs\sana\lib\site-packages\triton\testing.py", line 7, in <module>
    from . import language as tl
  File "e:\anaconda3\envs\sana\lib\site-packages\triton\language\__init__.py", line 4, in <module>
    from . import math
  File "e:\anaconda3\envs\sana\lib\site-packages\triton\language\math.py", line 1, in <module>
    from . import core
  File "e:\anaconda3\envs\sana\lib\site-packages\triton\language\core.py", line 10, in <module>
    from ..runtime.jit import jit
  File "e:\anaconda3\envs\sana\lib\site-packages\triton\runtime\jit.py", line 12, in <module>
    from ..runtime.driver import driver
  File "e:\anaconda3\envs\sana\lib\site-packages\triton\runtime\driver.py", line 1, in <module>
    from ..backends import backends
  File "e:\anaconda3\envs\sana\lib\site-packages\triton\backends\__init__.py", line 50, in <module>
    backends = _discover_backends()
  File "e:\anaconda3\envs\sana\lib\site-packages\triton\backends\__init__.py", line 43, in _discover_backends
    compiler = _load_module(name, os.path.join(root, name, 'compiler.py'))
  File "e:\anaconda3\envs\sana\lib\site-packages\triton\backends\__init__.py", line 12, in _load_module
    spec.loader.exec_module(module)
  File "e:\anaconda3\envs\sana\lib\site-packages\triton\backends\amd\compiler.py", line 2, in <module>
    from triton._C.libtriton import ir, passes, llvm, amd
ImportError: DLL load failed while importing libtriton: A dynamic link library (DLL) initialization routine failed.

**Comment by lawrence-cj** [comment]
pull the latest code

**Comment by CRCODE22** [comment]
> pull the latest code and maybe you can try to uninstall triton if the latest code still not work for you.

I tried does not work:

git clone https://github.com/NVlabs/Sana.git
conda create -n sana python=3.10.0 -y
conda activate sana
conda install -c nvidia cuda-toolkit -y
python -m pip install -U pip
pip install -U xformers==0.0.27.post2 --index-url https://download.pytorch.org/whl/cu121
pip install -e .
ERROR: Could not find a version that satisfies the requirement triton==3.0.0 (from sana) (from versions: none)
ERROR: No matching distribution found for triton==3.0.0

**Comment by CRCODE22** [comment]
Trying to run the software anyways will give more dependencies that are not installed.

(sana) K:\Sana>python app\app_sana.py --config configs\sana_config\1024ms\Sana_1600M_img1024.yaml --model_path Efficient-Large-Model\Sana_1600M_1024px\checkpoints\Sana_1600M_1024px.pth
Traceback (most recent call last):
  File "K:\Sana\app\app_sana.py", line 28, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'

**Comment by CRCODE22** [comment]
@lawrence-cj It should not be this difficult for you to make a working version for Windows?

**Comment by CRCODE22** [comment]
@nitinmukesh your installation of Windows also does not work similar problems.

**Comment by CRCODE22** [comment]
It does not look like anymore this model is even worth spending all that time on getting to work after days it still does not. Their devs clearly do not even know how to get it running on Windows 11.

pip install gradio

(sana) K:\Sana>python app\app_sana.py --config configs\sana_config\1024ms\Sana_1600M_img1024.yaml --model_path Efficient-Large-Model\Sana_1600M_1024px\checkpoints\Sana_1600M_1024px.pth
Traceback (most recent call last):
File "K:\Sana\app\app_sana.py", line 30, in
import spaces
ModuleNotFoundError: No module named 'spaces'

(sana) K:\Sana>pip install spaces

(sana) K:\Sana>python app\app_sana.py --config configs\sana_config\1024ms\Sana_1600M_img1024.yaml --model_path Efficient-Large-Model\Sana_1600M_1024px\checkpoints\Sana_1600M_1024px.pth
Traceback (most recent call last):
File "K:\Sana\app\app_sana.py", line 33, in
from torchvision.utils import make_grid, save_image
ModuleNotFoundError: No module named 'torchvision'

(sana) K:\Sana>pip install torchvision

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
xformers 0.0.27.post2 requires torch==2.4.0, but you have torch 2.5.1 which is incompatible.
Successfully installed torch-2.5.1 torchvision-0.20.1

**Comment by FurkanGozukara** [comment]
for who cant solve how to install i have 1 click installer that works

all you need is having installed python 3.10.11, cuda 12.x, c++ tools - public post : https://www.patreon.com/posts/nvidia-labs-sana-116531341

I spent 12 hours to make this installer + the improved gradio

![01 (1)](https://github.com/user-attachments/assets/6f694c1b-dae0-4856-8701-cb7d34b04ec6)

**Comment by lawrence-cj** [comment]
> ERROR: Could not find a version that satisfies the requirement triton==3.0.0 (from sana) (from versions: none)
ERROR: No matching distribution found for triton==3.0.0

The error stops the process of installing other dependencies, like I like remove the triton related part, like: 
https://github.com/NVlabs/Sana/blob/5765093947cbf7053463a8835974575da1278017/pyproject.toml#L44

And I'll try to remove the dependency of triton later when I'm free. The bandwidth is full. @CRCODE22

**Comment by newgenai79** [comment]
> No module named 'gradio'

pip install gradio

**Comment by CRCODE22** [comment]
> > ERROR: Could not find a version that satisfies the requirement triton==3.0.0 (from sana) (from versions: none)
> > ERROR: No matching distribution found for triton==3.0.0
> 
> The error stops the process of installing other dependencies, like I like remove the triton related part, like:
> 
> https://github.com/NVlabs/Sana/blob/5765093947cbf7053463a8835974575da1278017/pyproject.toml#L44
> 
> And I'll try to remove the dependency of triton later when I'm free. The bandwidth is full. @CRCODE22

Ok it would really if you can remove the dependency of triton do I still need to install xformers?

**Comment by CRCODE22** [comment]
> > No module named 'gradio'
> 
> pip install gradio

If it where only that simple once you have installed that as I mentioned and shown in my earlier post it will keep asking for other dependencies that should go automatic. I will first try to remove that line 44 as @lawrence-cj and see if dependencies are automatically installed.

**Comment by CRCODE22** [comment]
@lawrence-cj I did a reinstall and removed the line 44 related to triton on Sana/pyproject.toml](https://github.com/NVlabs/Sana/blob/5765093947cbf7053463a8835974575da1278017/pyproject.toml#L44)

(sana) K:\Sana>python app\app_sana.py --config configs\sana_config\1024ms\Sana_1600M_img1024.yaml --model_path Efficient-Large-Model\Sana_1600M_1024px\checkpoints\Sana_1600M_1024px.pth
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.4.0+cu121 with CUDA 1201 (you have 2.4.0+cpu)
    Python  3.10.11 (you have 3.10.15)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
Traceback (most recent call last):
  File "K:\Sana\app\app_sana.py", line 37, in <module>
    from app.sana_pipeline import SanaPipeline
  File "K:\Sana\app\sana_pipeline.py", line 28, in <module>
    from diffusion import DPMS, FlowEuler
  File "K:\Sana\diffusion\__init__.py", line 6, in <module>
    from .dpm_solver import DPMS
  File "K:\Sana\diffusion\dpm_solver.py", line 20, in <module>
    from .model.dpm_solver import DPM_Solver, NoiseScheduleFlow, NoiseScheduleVP, model_wrapper
  File "K:\Sana\diffusion\model\dpm_solver.py", line 23, in <module>
    from .nets.sana_blocks import (
  File "K:\Sana\diffusion\model\nets\__init__.py", line 1, in <module>
    from .sana import (
  File "K:\Sana\diffusion\model\nets\sana.py", line 25, in <module>
    from diffusion.model.builder import MODELS
  File "K:\Sana\diffusion\model\builder.py", line 24, in <module>
    from diffusion.model.dc_ae.efficientvit.ae_model_zoo import DCAE_HF
  File "K:\Sana\diffusion\model\dc_ae\efficientvit\ae_model_zoo.py", line 24, in <module>
    from ..efficientvit.models.efficientvit.dc_ae import DCAE, DCAEConfig, dc_ae_f32c32, dc_ae_f64c128, dc_ae_f128c512
  File "K:\Sana\diffusion\model\dc_ae\efficientvit\models\efficientvit\__init__.py", line 1, in <module>
    from .dc_ae import *
  File "K:\Sana\diffusion\model\dc_ae\efficientvit\models\efficientvit\dc_ae.py", line 25, in <module>
    from ...models.nn.act import build_act
  File "K:\Sana\diffusion\model\dc_ae\efficientvit\models\nn\__init__.py", line 2, in <module>
    from .drop import *
  File "K:\Sana\diffusion\model\dc_ae\efficientvit\models\nn\drop.py", line 24, in <module>
    from ...models.nn.ops import IdentityLayer, ResidualBlock
  File "K:\Sana\diffusion\model\dc_ae\efficientvit\models\nn\ops.py", line 24, in <module>
    from ...models.nn.norm import build_norm
  File "K:\Sana\diffusion\model\dc_ae\efficientvit\models\nn\norm.py", line 23, in <module>
    from ...models.nn.triton_rms_norm import TritonRMSNorm2dFunc
  File "K:\Sana\diffusion\model\dc_ae\efficientvit\models\nn\triton_rms_norm.py", line 18, in <module>
    import triton
ModuleNotFoundError: No module named 'triton'

(sana) K:\Sana>pip install -U xformers==0.0.27.post2 --index-url https://download.pytorch.org/whl/cu121
Looking in indexes: https://download.pytorch.org/whl/cu121, https://pypi.ngc.nvidia.com
Requirement already satisfied: xformers==0.0.27.post2 in e:\anaconda3\envs\sana\lib\site-packages (0.0.27.post2)
Requirement already satisfied: numpy in e:\anaconda3\envs\sana\lib\site-packages (from xformers==0.0.27.post2) (1.26.3)
Requirement already satisfied: torch==2.4.0 in e:\anaconda3\envs\sana\lib\site-packages (from xformers==0.0.27.post2) (2.4.0)
Requirement already satisfied: filelock in e:\anaconda3\envs\sana\lib\site-packages (from torch==2.4.0->xformers==0.0.27.post2) (3.13.1)
Requirement already satisfied: typing-extensions>=4.8.0 in e:\anaconda3\envs\sana\lib\site-packages (from torch==2.4.0->xformers==0.0.27.post2) (4.12.2)
Requirement already satisfied: sympy in e:\anaconda3\envs\sana\lib\site-packages (from torch==2.4.0->xformers==0.0.27.post2) (1.13.1)
Requirement already satisfied: networkx in e:\anaconda3\envs\sana\lib\site-packages (from torch==2.4.0->xformers==0.0.27.post2) (3.2.1)
Requirement already satisfied: jinja2 in e:\anaconda3\envs\sana\lib\site-packages (from torch==2.4.0->xformers==0.0.27.post2) (3.1.3)
Requirement already satisfied: fsspec in e:\anaconda3\envs\sana\lib\site-packages (from torch==2.4.0->xformers==0.0.27.post2) (2024.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in e:\anaconda3\envs\sana\lib\site-packages (from jinja2->torch==2.4.0->xformers==0.0.27.post2) (2.1.5)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in e:\anaconda3\envs\sana\lib\site-packages (from sympy->torch==2.4.0->xformers==0.0.27.post2) (1.3.0)

(sana) K:\Sana>python app\app_sana.py --config configs\sana_config\1024ms\Sana_1600M_img1024.yaml --model_path Efficient-Large-Model\Sana_1600M_1024px\checkpoints\Sana_1600M_1024px.pth
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.4.0+cu121 with CUDA 1201 (you have 2.4.0+cpu)
    Python  3.10.11 (you have 3.10.15)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
Traceback (most recent call last):
  File "K:\Sana\app\app_sana.py", line 37, in <module>
    from app.sana_pipeline import SanaPipeline
  File "K:\Sana\app\sana_pipeline.py", line 28, in <module>
    from diffusion import DPMS, FlowEuler
  File "K:\Sana\diffusion\__init__.py", line 6, in <module>
    from .dpm_solver import DPMS
  File "K:\Sana\diffusion\dpm_solver.py", line 20, in <module>
    from .model.dpm_solver import DPM_Solver, NoiseScheduleFlow, NoiseScheduleVP, model_wrapper
  File "K:\Sana\diffusion\model\dpm_solver.py", line 23, in <module>
    from .nets.sana_blocks import (
  File "K:\Sana\diffusion\model\nets\__init__.py", line 1, in <module>
    from .sana import (
  File "K:\Sana\diffusion\model\nets\sana.py", line 25, in <module>
    from diffusion.model.builder import MODELS
  File "K:\Sana\diffusion\model\builder.py", line 24, in <module>
    from diffusion.model.dc_ae.efficientvit.ae_model_zoo import DCAE_HF
  File "K:\Sana\diffusion\model\dc_ae\efficientvit\ae_model_zoo.py", line 24, in <module>
    from ..efficientvit.models.efficientvit.dc_ae import DCAE, DCAEConfig, dc_ae_f32c32, dc_ae_f64c128, dc_ae_f128c512
  File "K:\Sana\diffusion\model\dc_ae\efficientvit\models\efficientvit\__init__.py", line 1, in <module>
    from .dc_ae import *
  File "K:\Sana\diffusion\model\dc_ae\efficientvit\models\efficientvit\dc_ae.py", line 25, in <module>
    from ...models.nn.act import build_act
  File "K:\Sana\diffusion\model\dc_ae\efficientvit\models\nn\__init__.py", line 2, in <module>
    from .drop import *
  File "K:\Sana\diffusion\model\dc_ae\efficientvit\models\nn\drop.py", line 24, in <module>
    from ...models.nn.ops import IdentityLayer, ResidualBlock
  File "K:\Sana\diffusion\model\dc_ae\efficientvit\models\nn\ops.py", line 24, in <module>
    from ...models.nn.norm import build_norm
  File "K:\Sana\diffusion\model\dc_ae\efficientvit\models\nn\norm.py", line 23, in <module>
    from ...models.nn.triton_rms_norm import TritonRMSNorm2dFunc
  File "K:\Sana\diffusion\model\dc_ae\efficientvit\models\nn\triton_rms_norm.py", line 18, in <module>
    import triton
ModuleNotFoundError: No module named 'triton'

**Comment by CRCODE22** [comment]
I solved most of the problems but the triton requirement is still hard coded it seems and prevents Sana from working on Windows 11

(sana) K:\Sana>python app\app_sana.py --config configs\sana_config\1024ms\Sana_1600M_img1024.yaml --model_path Efficient-Large-Model\Sana_1600M_1024px\checkpoints\Sana_1600M_1024px.pth
A matching Triton is not available, some optimizations will not be enabled
Traceback (most recent call last):
  File "e:\anaconda3\envs\sana\lib\site-packages\xformers\__init__.py", line 57, in _is_triton_available
    import triton  # noqa
ModuleNotFoundError: No module named 'triton'
Traceback (most recent call last):
  File "K:\Sana\app\app_sana.py", line 37, in <module>
    from app.sana_pipeline import SanaPipeline
  File "K:\Sana\app\sana_pipeline.py", line 28, in <module>
    from diffusion import DPMS, FlowEuler
  File "K:\Sana\diffusion\__init__.py", line 6, in <module>
    from .dpm_solver import DPMS
  File "K:\Sana\diffusion\dpm_solver.py", line 20, in <module>
    from .model.dpm_solver import DPM_Solver, NoiseScheduleFlow, NoiseScheduleVP, model_wrapper
  File "K:\Sana\diffusion\model\dpm_solver.py", line 23, in <module>
    from .nets.sana_blocks import (
  File "K:\Sana\diffusion\model\nets\__init__.py", line 1, in <module>
    from .sana import (
  File "K:\Sana\diffusion\model\nets\sana.py", line 25, in <module>
    from diffusion.model.builder import MODELS
  File "K:\Sana\diffusion\model\builder.py", line 24, in <module>
    from diffusion.model.dc_ae.efficientvit.ae_model_zoo import DCAE_HF
  File "K:\Sana\diffusion\model\dc_ae\efficientvit\ae_model_zoo.py", line 24, in <module>
    from ..efficientvit.models.efficientvit.dc_ae import DCAE, DCAEConfig, dc_ae_f32c32, dc_ae_f64c128, dc_ae_f128c512
  File "K:\Sana\diffusion\model\dc_ae\efficientvit\models\efficientvit\__init__.py", line 1, in <module>
    from .dc_ae import *
  File "K:\Sana\diffusion\model\dc_ae\efficientvit\models\efficientvit\dc_ae.py", line 25, in <module>
    from ...models.nn.act import build_act
  File "K:\Sana\diffusion\model\dc_ae\efficientvit\models\nn\__init__.py", line 2, in <module>
    from .drop import *
  File "K:\Sana\diffusion\model\dc_ae\efficientvit\models\nn\drop.py", line 24, in <module>
    from ...models.nn.ops import IdentityLayer, ResidualBlock
  File "K:\Sana\diffusion\model\dc_ae\efficientvit\models\nn\ops.py", line 24, in <module>
    from ...models.nn.norm import build_norm
  File "K:\Sana\diffusion\model\dc_ae\efficientvit\models\nn\norm.py", line 23, in <module>
    from ...models.nn.triton_rms_norm import TritonRMSNorm2dFunc
  File "K:\Sana\diffusion\model\dc_ae\efficientvit\models\nn\triton_rms_norm.py", line 18, in <module>
    import triton
ModuleNotFoundError: No module named 'triton'

**Comment by yujincheng08** [comment]
#80

**Comment by FurkanGozukara** [comment]
over a month and fcntl is still not fixed mind blowing

**Comment by AfterHAL** [comment]
> over a month and fcntl is still not fixed mind blowing

How the hell don't you know about Windows Subsystem for Linux ?
Don't be afraid to use it, your mind will not literally Blow.
And, by the way, learn how to use punctuation in your sentences... please.
