### ISSUE TITLE
models can't be loaded

### ISSUE THREAD

**Issue by Bocchi-Chan2023** [NVlabs/Sana#40]
~/Sana$ DEMO_PORT=15432 python app/app_sana.py       --config=configs/sana_config/1024ms/Sana_1600M_img1024.yaml       --model_path=hf://Efficient-Large-Model/Sana_1600M_1024px/checkpoints/Sana_1600M_1024px.pth
2024-11-24 23:37:37 - [Sana] - INFO - Sampler flow_dpm-solver, flow_shift: 3.0
2024-11-24 23:37:37 - [Sana] - INFO - Inference with torch.float16, PAG guidance layer: [8]
[DC-AE] Loading model from mit-han-lab/dc-ae-f32c32-sana-1.0
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  4.50it/s]
2024-11-24 23:37:58 - [Sana] - WARNING - use pe: False, position embed interpolation: 1.0, base size: 32
2024-11-24 23:37:58 - [Sana] - WARNING - attention type: linear; ffn type: glumbconv; autocast linear attn: False
2024-11-24 23:38:09 - [Sana] - INFO - use_fp32_attention: True
2024-11-24 23:38:09 - [Sana] - INFO - SanaMS:SanaMS_1600M_P1_D20,Model Parameters: 1,604,462,752
Fetching 4 files: 100%|█████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 4848.91it/s]
[Sana] Loading model from /home/moon/.cache/huggingface/hub/models--Efficient-Large-Model--Sana_1600M_1024px/snapshots/bc305d7162d18570064236b17a3732dff1d57861/checkpoints/Sana_1600M_1024px.pth
2024-11-24 23:38:15 - [Sana] - INFO - Generating sample from ckpt: hf://Efficient-Large-Model/Sana_1600M_1024px/checkpoints/Sana_1600M_1024px.pth
2024-11-24 23:38:15 - [Sana] - WARNING - Missing keys: ['pos_embed']
2024-11-24 23:38:15 - [Sana] - WARNING - Unexpected keys: []
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.25it/s]
Some parameters are on the meta device because they were offloaded to the cpu.
You shouldn't move a model that is dispatched using accelerate hooks.
Traceback (most recent call last):
  File "/home/moon/Sana/app/app_sana.py", line 203, in <module>
    ).to(device)
  File "/home/moon/miniconda3/envs/sana/lib/python3.10/site-packages/accelerate/big_modeling.py", line 456, in wrapper
    raise RuntimeError("You can't move a model that has some modules offloaded to cpu or disk.")
RuntimeError: You can't move a model that has some modules offloaded to cpu or disk.

I did reinstalling conda, git pull and git stash and it didn't work with the same error.

**Comment by Bocchi-Chan2023** [comment]
removing safety checker fixed this

**Comment by Bocchi-Chan2023** [comment]
still happening, I have to remove safety_checker from demo

**Comment by mmlingyu** [comment]
the same problems with rtx 2080ti  12g
