### ISSUE TITLE
Vanilla Attention Inference Precision Error

### ISSUE THREAD

**Issue by ysl6323** [NVlabs/Sana#82]
My deepest gratitude for your brilliant open-sourced work.

Someday when I was trying to create and train my own super small version of Sana, which has an attn_type of vanilla and ffn_type of mbconvpreglu (detailed setting in this image below)
![image](https://github.com/user-attachments/assets/8dafc45b-6c56-44fa-b4cf-f38d1208bcd2)

And then strange things come. I can finish the training process without any resistance. But when I inference with my fresh ckpt, an error ruthlessly interrupted my process. Detailed Error report shown below.

(sana) user@machine:/data/usr/Sana$ python scripts/inference.py       --config=/data/usr/Sana/configs/sana_config/512ms/Sana_200M_img512.yaml       --model_path=/data/usr/Sana/output/debug/checkpoints/epoch_1_step_939.pth       --txt_file=/data/usr/Sana/test_prompt.txt  --step=20
2024-12-11 17:25:06 - [Sana] - INFO - Inference with torch.float16, default guidance_type: classifier-free_PAG, flow_shift: 1.0
[DC-AE] Loading model from mit-han-lab/dc-ae-f32c32-sana-1.0
2024-12-11 17:25:13 - [Sana] - WARNING - use pe: False, position embed interpolation: 1.0, base size: 32
2024-12-11 17:25:13 - [Sana] - WARNING - attention type: vanilla; ffn type: mbconvpreglu; autocast linear attn: False
2024-12-11 17:25:13 - [Sana] - INFO - Sana:Sana_200M_P1_D14, Model Parameters: 134,128,160
2024-12-11 17:25:13 - [Sana] - INFO - Generating sample from ckpt: /data/usr/Sana/output/debug/checkpoints/epoch_1_step_939.pth
[Sana] Loading model from /data/usr/Sana/output/debug/checkpoints/epoch_1_step_939.pth
2024-12-11 17:25:13 - [Sana] - WARNING - Missing keys: ['pos_embed']
2024-12-11 17:25:13 - [Sana] - WARNING - Unexpected keys: []
2024-12-11 17:25:13 - [Sana] - INFO - Saving images at output/inference
2024-12-11 17:25:13 - [Sana] - INFO - Eval first 10/10 samples
2024-12-11 17:25:13 - [Sana] - INFO - Sampler flow_dpm-solver
2024-12-11 17:25:13 - [Sana] - INFO - Setting back to classifier-free
2024-12-11 17:25:13 - [Sana] - INFO - Inference with torch.float16, guidance_type: classifier-free, flow_shift: 1.0
custom_epoch1_step939_scale4.5_step20_size512_bs1_sampflow_dpm-solver_seed0_float16_imgnums100000 Using GPU: 0: 0-30000:   0%|            | 0/10 [00:00<?, ?batch/s]
Traceback (most recent call last):
  File "/data/usr/Sana/diffusion/model/dpm_solver.py", line 441, in model_fn
    noise_uncond, noise = noise_pred_fn(x_in, t_in, cond=c_in).chunk(2)
  File "/data/usr/Sana/diffusion/model/dpm_solver.py", line 386, in noise_pred_fn
    output = model(x, t_input, cond, **model_kwargs)
  File "/data/usr/Sana/diffusion/model/nets/sana.py", line 318, in __call__
    return self.forward(*args, **kwargs)
  File "/data/usr/Sana/diffusion/model/nets/sana.py", line 308, in forward
    x = auto_grad_checkpoint(block, x, y, t0, y_lens)  # (N, T, D) #support grad checkpoint
  File "/data/usr/Sana/diffusion/model/utils.py", line 73, in auto_grad_checkpoint
    return module(*args, **kwargs)
  File "/home/usr/miniconda3/envs/sana/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/usr/miniconda3/envs/sana/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/usr/Sana/diffusion/model/nets/sana.py", line 164, in forward
    x = x + self.drop_path(gate_msa * self.attn(t2i_modulate(self.norm1(x), shift_msa, scale_msa)).reshape(B, N, C))
  File "/home/usr/miniconda3/envs/sana/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/usr/miniconda3/envs/sana/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/usr/Sana/diffusion/model/nets/sana_blocks.py", line 405, in forward
    x = (attn @ v).transpose(1, 2).reshape(B, N, C)
RuntimeError: expected scalar type Half but found Float

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/usr/Sana/scripts/inference.py", line 464, in <module>
    visualize(
  File "/home/usr/miniconda3/envs/sana/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/data/usr/Sana/scripts/inference.py", line 201, in visualize
    samples = dpm_solver.sample(
  File "/data/usr/Sana/diffusion/model/dpm_solver.py", line 1529, in sample
    model_prev_list = [self.model_fn(x, t)]
  File "/data/usr/Sana/diffusion/model/dpm_solver.py", line 689, in model_fn
    return self.data_prediction_fn(x, t)
  File "/data/usr/Sana/diffusion/model/dpm_solver.py", line 677, in data_prediction_fn
    noise = self.noise_prediction_fn(x, t)
  File "/data/usr/Sana/diffusion/model/dpm_solver.py", line 671, in noise_prediction_fn
    return self.model(x, t)
  File "/data/usr/Sana/diffusion/model/dpm_solver.py", line 616, in <lambda>
    self.model = lambda x, t: model_fn(x, t.expand(x.shape[0]))
  File "/data/usr/Sana/diffusion/model/dpm_solver.py", line 443, in model_fn
    noise_uncond, noise = noise_pred_fn(x_in, t_in, cond=c_in)[0].chunk(2)
  File "/data/usr/Sana/diffusion/model/dpm_solver.py", line 386, in noise_pred_fn
    output = model(x, t_input, cond, **model_kwargs)
  File "/data/usr/Sana/diffusion/model/nets/sana.py", line 318, in __call__
    return self.forward(*args, **kwargs)
  File "/data/usr/Sana/diffusion/model/nets/sana.py", line 308, in forward
    x = auto_grad_checkpoint(block, x, y, t0, y_lens)  # (N, T, D) #support grad checkpoint
  File "/data/usr/Sana/diffusion/model/utils.py", line 73, in auto_grad_checkpoint
    return module(*args, **kwargs)
  File "/home/usr/miniconda3/envs/sana/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/usr/miniconda3/envs/sana/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/usr/Sana/diffusion/model/nets/sana.py", line 164, in forward
    x = x + self.drop_path(gate_msa * self.attn(t2i_modulate(self.norm1(x), shift_msa, scale_msa)).reshape(B, N, C))
  File "/home/usr/miniconda3/envs/sana/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/usr/miniconda3/envs/sana/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/usr/Sana/diffusion/model/nets/sana_blocks.py", line 405, in forward
    x = (attn @ v).transpose(1, 2).reshape(B, N, C)
RuntimeError: expected scalar type Half but found Float

Dataset and model hyperparameters were set small for I just need to finish a feasibility-oriented experiment.
It seems that the problem arises from a precision collision. Do you have any btilliant insights into the bug I am encountering?

**Comment by ysl6323** [comment]
Thanks a lot!
